### ISSUE TITLE
Needs libssh-dev to compile

### ISSUE THREAD

**Issue by Ibrahimous** [0x90/openssh-sftp-sploit#1]
Hi,
Thanks for your work. Just a self-resolved issue, when getting the following error:
```
root@kali:~# gcc sshsploit.c -o sshsploit -std=c99 -lssh
sshsploit.c:18:10: fatal error: libssh/libssh.h: No such file or directory
 #include <libssh/libssh.h>
          ^~~~~~~~~~~~~~~~~
```

... you need to install libssh-dev:
`root@kali:~# aptitude -ry install libssh-dev`

**Comment by Naategh** [comment]
Thank you, worked for me :)

**Comment by ozcanay** [comment]
libssh-devel for centOs and fedora.
